### ISSUE TITLE
isModule 为 true时，不能直接运行app

### ISSUE THREAD

**Issue by liyanlei666** [guiying712/AndroidModulePattern#1]
![temp222 1](https://cloud.githubusercontent.com/assets/17938429/24538586/c1679576-161c-11e7-906e-c679ac0d86ad.png)

在设计的时候，就不能在isModule 为 true时，不能直接运行app么？

**Comment by guiying712** [comment]
其实app组件是一个空壳，只负责管理其他组件，肯定不能独立运行，我已经调整了架构，你可以查看最新的代码。

**Comment by liyanlei666** [comment]
好的。明确
