### ISSUE TITLE
Android Studio 3.0.1: Failed to Failed to resolve ...

### ISSUE THREAD

**Issue by JinnyZh** [guiying712/AndroidModulePattern#11]
Error:Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1
Error:Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
Error:Failed to resolve: .....

How to resolve this problem?

**Comment by JinnyZh** [comment]
c4870b64fa781d511ec451f92482268e65e341a3 is OK in Android Studio 2.2.3

**Comment by guiying712** [comment]
AndroidStudio3.0使用了Google仓库，所以需要自带梯子才能通过编译

**Comment by StephenGiant** [comment]
哥们，你把这三个库的版本写死就可以了

**Comment by JinnyZh** [comment]
add maven { url "https://jitpack.io" }
