### ISSUE TITLE
项目导入出错

### ISSUE THREAD

**Issue by huatx** [guiying712/AndroidModulePattern#13]
D:\demo\AndroidModulePattern-master\AndroidModulePattern-master\module_girls\build.gradle
    Error:Error:Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_girls/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_girls/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.GrenderG:Toasty:1.1.3
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_girls/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
D:\demo\AndroidModulePattern-master\AndroidModulePattern-master\module_main\build.gradle
    Error:Error:Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_main/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_main/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.GrenderG:Toasty:1.1.3
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_main/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
D:\demo\AndroidModulePattern-master\AndroidModulePattern-master\module_app\build.gradle
    Error:Error:Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.GrenderG:Toasty:1.1.3
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
D:\demo\AndroidModulePattern-master\AndroidModulePattern-master\lib_common\build.gradle
    Error:Error:Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/lib_common/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/lib_common/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.GrenderG:Toasty:1.1.3
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/lib_common/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
D:\demo\AndroidModulePattern-master\AndroidModulePattern-master\module_news\build.gradle
    Error:Error:Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_news/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.chrisbanes:PhotoView:2.0.0
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_news/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.github.GrenderG:Toasty:1.1.3
<a href="openFile:D:/demo/AndroidModulePattern-master/AndroidModulePattern-master/module_news/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

AndroidStudio 版本3.0

**Comment by guiying712** [comment]
allprojects {
    repositories {
        ...
        //Add the JitPack repository
        maven { url "https://jitpack.io" }
    }
}
