### ISSUE TITLE
Fragment 如何模块化?

### ISSUE THREAD

**Issue by LoveqLRC** [guiying712/AndroidModulePattern#2]
例如微信那样的布局，4`Tab`的都是`fragment`填充，如何组件化?我看了一些组件化的文章都是以`Activity`为单位进行，而实际开发中往往是一个`Activity`带几个`Fragment`。

**Comment by guiying712** [comment]
推荐Router使用阿里的ARouter，然后通过：
Fragment fragment = (Fragment) ARouter.getInstance().build("/test/fragment").navigation();
 获取Fragment ，这样Fragment就可以随意放在任何一个组件中。

**Comment by LoveqLRC** [comment]
好的，谢谢，我试一下
