### ISSUE TITLE
关于在子模块中编写代码时，application context 的引用

### ISSUE THREAD

**Issue by tosslife** [guiying712/AndroidModulePattern#4]
子模块只在debug时才有 application 里面只能做一些初始化操作，
后续打包时这些初始化都在主模块app 初始化，
子model中的application是单独调试子模块时候使用，
子model内编写代马时，一定注意不能使用 application context 的 ，
不知我说的对吗？

**Comment by guiying712** [comment]
application context 任何时候都可以使用，但是只能使用BaseApplication中Context，并且这个BaseApplication要被声明或者继承；
