### ISSUE TITLE
运行点击报错了

### ISSUE THREAD

**Issue by zhouguanglian** [guiying712/AndroidModulePattern#5]
![tim 20170804143507](https://user-images.githubusercontent.com/9064262/28956975-451d5f96-7922-11e7-83eb-8f4c49586fde.png)

**Comment by guiying712** [comment]
请问这个问题是怎么出现的？能具体点吗

**Comment by zhouguanglian** [comment]
我直接down下来运行就报错了

**Comment by zhouguanglian** [comment]
![image](https://user-images.githubusercontent.com/9064262/29200041-926a39c4-7e84-11e7-9b56-9b7363035e29.png)
ji就是点击这两个都不能进入，报错。

**Comment by houmengdi** [comment]
老铁，就是报这个错！！！

**Comment by guiying712** [comment]
原因已经找到，这两个组件中使用的网络请求接口都已经发生了变化，知乎和干活的的接口都已经不能用了

**Comment by guiying712** [comment]
老铁，我试了没毛病啊

**Comment by houmengdi** [comment]
![_20170815102053](https://user-images.githubusercontent.com/17944692/29299755-b3538772-81a3-11e7-9877-b14d1b3c5647.png)

**Comment by guiying712** [comment]
你们是在集成开发模式还是组件开发模式啊？

**Comment by guiying712** [comment]
从新拉下代码试试

**Comment by houmengdi** [comment]
isModule我已经改成了集成开发模式，路由就是没法调

**Comment by houmengdi** [comment]
好了，问题找到了

**Comment by Lemonqsj** [comment]
两个都不能点击,在主module上

**Comment by guiying712** [comment]
什么问题？给其他说下，我怎么就没碰到什么问题。

**Comment by houmengdi** [comment]
我是改了gradle才出现的，那个注解解释器我全部放在了common里面了，其实每个module里面都得配置！！

**Comment by houmengdi** [comment]
还有就是集成模式时，必须运行app才行，组件模式下只能单个模块运行除了app模块

**Comment by houmengdi** [comment]
他们可能在组件模式下运行了main module

**Comment by guiying712** [comment]
你代码都改了，你也是厉害啊。

**Comment by cheetah747** [comment]
Error:(5, 5) 错误: 找不到符号
符号:   变量 RouterMapping_main
位置: 类 RouterInit
我没改代码。。。。直接拉下来，就改了个isModule为true,然后sync gradle，然后对module_news单独编译，就报错了。这咋整啊？？？（isModule为false的时候assembleDebug可以成功）

**Comment by guiying712** [comment]
检查下main组件的声明还在不在了，就是这个注解@Module

**Comment by cheetah747** [comment]
在的呀。@Module("main")
public class Main {
}

**Comment by Lemonqsj** [comment]
还是不可以运行,我拉下来直接运行就报错,

Error:(5, 5) 错误: 找不到符号
符号:   变量 RouterMapping_main
位置: 类 RouterInit
Error:(6, 5) 错误: 找不到符号
符号:   变量 RouterMapping_girls
位置: 类 RouterInit
Error:(7, 5) 错误: 找不到符号
符号:   变量 RouterMapping_news
位置: 类 RouterInit

**Comment by guiying712** [comment]
请进我博客加我微信，方便解决问题，不然我根本没法判断你是怎么做的

**Comment by Edison0716** [comment]
大佬 加个微信 想请教你下

**Comment by Edison0716** [comment]
谢谢
