### ISSUE TITLE
请求数据的解析

### ISSUE THREAD

**Issue by summer0906** [guiying712/AndroidModulePattern#6]
看了作者博客过来的,对使用Retrofit2封装适用于组件化项目的网络库挺感兴趣.不过有一个疑问,在HttpClient中数据的解析好像是在主线程处理的,这样感觉有点不太好吧,有没有什么改进的办法呢?

**Comment by guiying712** [comment]
我觉得这个可以学习下Retrofit的默认解析数据方式 addConverterFactory(GsonConverterFactory.create())，可以看看这个里面代码是怎么实现的。
