### ISSUE TITLE
如果不用router是否可行？

### ISSUE THREAD

**Issue by zhangruize** [guiying712/AndroidModulePattern#7]
您好，我在尝试这种方案的时候，试图不使用router，虽然可以通过增加compile project从而在跳转的时候直接使用intent(this, another_module.class)，但是会遇到问题。比如：从application向其他lib的activity时完全可以，但其他的lib要跳到application的activity就会遇到麻烦，因为那些lib需要依赖一个application，build时不通过。
可能我上述还是有些难以难以理清，不过想先问下有没有试过没有router也可使用此方案呢？

**Comment by guiying712** [comment]
不用Router当然是可以的，另一种方案就是使用接口，A组件要想被B组件启动，那么A组件就可以提供一个接口库，这个库由A和B同时依赖，B就可以启动A组件了。

**Comment by zhangruize** [comment]
嗯，加库……那其实我在尝试的时候，发现似乎也可以不必为每个module都使用两个manifest文件，保留一个manifest并加入intent-filter，在lib作为application时可以运行，在lib作为lib时也似乎被自动忽略。

**Comment by guiying712** [comment]
如果这样的话一个应用会出现很多个启动Activity，你的手机上会显示好几个APP图标，点击每一个图标都会进入不同的启动Activity。

**Comment by zhangruize** [comment]
通过上手尝试感觉逐渐掌握这种组件化方式了~博主在实际运用中有没有碰到什么坑或者这种方式的缺陷、不足的呢？
